// Generated by view binder compiler. Do not edit!
package com.example.moodtracker.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.moodtracker.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityReasonBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final EditText reasonInput;

  @NonNull
  public final Button saveReasonButton;

  @NonNull
  public final ImageView selectedMoodImage;

  @NonNull
  public final TextView selectedMoodText;

  private ActivityReasonBinding(@NonNull LinearLayout rootView, @NonNull EditText reasonInput,
      @NonNull Button saveReasonButton, @NonNull ImageView selectedMoodImage,
      @NonNull TextView selectedMoodText) {
    this.rootView = rootView;
    this.reasonInput = reasonInput;
    this.saveReasonButton = saveReasonButton;
    this.selectedMoodImage = selectedMoodImage;
    this.selectedMoodText = selectedMoodText;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityReasonBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityReasonBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_reason, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityReasonBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.reasonInput;
      EditText reasonInput = ViewBindings.findChildViewById(rootView, id);
      if (reasonInput == null) {
        break missingId;
      }

      id = R.id.saveReasonButton;
      Button saveReasonButton = ViewBindings.findChildViewById(rootView, id);
      if (saveReasonButton == null) {
        break missingId;
      }

      id = R.id.selectedMoodImage;
      ImageView selectedMoodImage = ViewBindings.findChildViewById(rootView, id);
      if (selectedMoodImage == null) {
        break missingId;
      }

      id = R.id.selectedMoodText;
      TextView selectedMoodText = ViewBindings.findChildViewById(rootView, id);
      if (selectedMoodText == null) {
        break missingId;
      }

      return new ActivityReasonBinding((LinearLayout) rootView, reasonInput, saveReasonButton,
          selectedMoodImage, selectedMoodText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
