// Generated by view binder compiler. Do not edit!
package com.example.moodtracker.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.CheckBox;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.moodtracker.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ItemHistoryBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final CheckBox historyCheckBox;

  @NonNull
  public final TextView historyMoodDate;

  @NonNull
  public final ImageView historyMoodImage;

  @NonNull
  public final TextView historyMoodName;

  @NonNull
  public final TextView historyMoodReason;

  private ItemHistoryBinding(@NonNull LinearLayout rootView, @NonNull CheckBox historyCheckBox,
      @NonNull TextView historyMoodDate, @NonNull ImageView historyMoodImage,
      @NonNull TextView historyMoodName, @NonNull TextView historyMoodReason) {
    this.rootView = rootView;
    this.historyCheckBox = historyCheckBox;
    this.historyMoodDate = historyMoodDate;
    this.historyMoodImage = historyMoodImage;
    this.historyMoodName = historyMoodName;
    this.historyMoodReason = historyMoodReason;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemHistoryBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemHistoryBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_history, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemHistoryBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.historyCheckBox;
      CheckBox historyCheckBox = ViewBindings.findChildViewById(rootView, id);
      if (historyCheckBox == null) {
        break missingId;
      }

      id = R.id.historyMoodDate;
      TextView historyMoodDate = ViewBindings.findChildViewById(rootView, id);
      if (historyMoodDate == null) {
        break missingId;
      }

      id = R.id.historyMoodImage;
      ImageView historyMoodImage = ViewBindings.findChildViewById(rootView, id);
      if (historyMoodImage == null) {
        break missingId;
      }

      id = R.id.historyMoodName;
      TextView historyMoodName = ViewBindings.findChildViewById(rootView, id);
      if (historyMoodName == null) {
        break missingId;
      }

      id = R.id.historyMoodReason;
      TextView historyMoodReason = ViewBindings.findChildViewById(rootView, id);
      if (historyMoodReason == null) {
        break missingId;
      }

      return new ItemHistoryBinding((LinearLayout) rootView, historyCheckBox, historyMoodDate,
          historyMoodImage, historyMoodName, historyMoodReason);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
